# This is a basic workflow to help you get started with Actions

name: Explore

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}
      PYTHON_CMD: "python${{ matrix.python-version }}"
      PYTHON_VER: "${{ matrix.python-version }}"

    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: ['3.6', '3.7', '3.8']
        compiler: ['gcc', 'clang']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Depends
        run: sh -x scripts/do-install_depends.sh

      - name: Explore
        run: sh -x scripts/do-explore.sh

      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: visual_bitstream_representation
          path: dtmf_2021_H_02_H_18.png
